plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Layout/TrailingEmptyLines:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
